# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'collectionview2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for collectionview2
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'IBAnimatable'
  pod 'Parchment'
  pod 'TextFieldEffects'
  pod 'OnOffButton'

end
